USE [master]
GO

/****** Object:  Database [MvcFriendContext]    Script Date: 20/01/2020 00:50:53 ******/
CREATE DATABASE [MvcFriendContext]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MvcFriendContext', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\MvcFriendContext.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MvcFriendContext_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\MvcFriendContext_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MvcFriendContext].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MvcFriendContext] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MvcFriendContext] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MvcFriendContext] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MvcFriendContext] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MvcFriendContext] SET ARITHABORT OFF 
GO

ALTER DATABASE [MvcFriendContext] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [MvcFriendContext] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MvcFriendContext] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MvcFriendContext] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MvcFriendContext] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MvcFriendContext] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MvcFriendContext] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MvcFriendContext] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MvcFriendContext] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MvcFriendContext] SET  ENABLE_BROKER 
GO

ALTER DATABASE [MvcFriendContext] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MvcFriendContext] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MvcFriendContext] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MvcFriendContext] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MvcFriendContext] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MvcFriendContext] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [MvcFriendContext] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MvcFriendContext] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MvcFriendContext] SET  MULTI_USER 
GO

ALTER DATABASE [MvcFriendContext] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MvcFriendContext] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MvcFriendContext] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MvcFriendContext] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MvcFriendContext] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MvcFriendContext] SET QUERY_STORE = OFF
GO

ALTER DATABASE [MvcFriendContext] SET  READ_WRITE 
GO

